facebook/src/com/facebook/login/LoginManager.java

Also, remind user to add the class to manifest.
This error can make developers run in loops for hours without realising which class name they have forgotten to add in their manifest.

correct the login class name in the log line

---

facebook/src/com/facebook/internal/WebDialog.java

If the user doesn't have the Facebook app installed, he/she will use webview to login/share. The webview is initialized with activity context instead of application context. So, the WeakHashMap cache inside ResourcesContextWrapperFactory will end up retaining a reference to the FacebookActivity forever. More details about the issue here: 
https://code.google.com/p/chromium/issues/detail?id=473146

fix leak with webview

---

facebook/src/com/facebook/FacebookButtonBase.java
facebook/src/com/facebook/share/widget/LikeView.java

Making getActivity support multilevel ContextWrapper to support passing extra information through multi-layered contextwrapping. (https://github.com/square/flow also uses contextwrapper to pass information this way)

unwrap multiple levels of ContextWrapper

---

.buckconfig
libs/BUCK

Summary:
Fix bolts jar filename in libs/ and update to Java 1.7.
Test Plan:
buck clean
buck build sdk
Blame Revision: D1512256
Blame Commit: d075400

Fix buck build

---

facebook/src/com/facebook/appevents/AppEventsLogger.java
facebook/src/com/facebook/login/LoginManager.java

LoginManager's ```context``` and ```loginLogger``` both hold a reference to the activity starting the login. This activity is leaked if the login process is canceled. It is also leaked if ```finishLogin()``` is never called, e.g. when the device's configuration/orientation is changed. ```finishLogin()``` only nulls out ```context``` and ```loginLogger``` in case of a successful login.
This commit updates ```LoginManager``` and ```AppEventsLogger```, so that it is not required anymore to hold a reference to the activity starting the login.

Fix memory leak in LoginManager / AppEventsLogger

---

facebook/src/com/facebook/login/LoginManager.java

No reason to keep pending login request after login execution

Clean pending request after login execution

---

facebook/junitTests/src/test/java/com/facebook/FacebookSdkPowerMockTest.java
facebook/src/com/facebook/FacebookSdk.java

It would be great to have opportunity to force applicationId to be string. Otherwise if you specify applicationId directly through Android manifest (not through constant in strings.xml file) it will overflow to 32-bit int instead of string. I suggest to support also applicationIds with prefix "fb" which will ensure that it will be parsed to string correctly. It will be also similar to CFBundleURLSchemes in iOS version of SDK which is also prefixed by "fb".

Support applicationId prefixed with "fb"

---

facebook/src/com/facebook/share/model/AppInviteContent.java

I used this class in Activity and it crashed my application because it is missing CREATOR http://developer.android.com/reference/android/os/Parcelable.html.

-added missing CREATOR to parcelable class AppInviteContent

---

facebook/src/com/facebook/internal/AttributionIdentifiers.java

This is currently breaking our app's request for custom audience third party IDs.

Actually return identifiers so method actually works.

---

.travis.yml

When target sdk was changed to v23 travis ci components were not updated.

Add missing travis ci components

---

facebook/src/com/facebook/GraphRequest.java

Add null check on attributionIdentifiers to prevent null pointer exceptions

---

facebook/src/main/java/com/facebook/appevents/AppEventsLogger.java

fix for relatively rare crashes like this:
com.facebook.AppEventsLogger(  706): Caught unexpected exception while flushing: java.lang.NullPointerException
java.lang.NullPointerException
at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:891)
at com.facebook.internal.Utility.queryAppSettings(Utility.java:364)
at com.facebook.AppEventsLogger$3.run(AppEventsLogger.java:623)
at java.util.Timer$TimerImpl.run(Timer.java:284)
It happens because static methods of AppEventsLogger and AppEventsLogger.PersistedEvents use different objects with same name for synchronization.

data race for AppEventsLogger.stateMap fixed

---

facebook/build.gradle

Running `gradle dependencies` on my Android project I see the following result
```
[…]
+--- com.facebook.android:facebook-android-sdk:4.9.0
|    +--- com.parse.bolts:bolts-applinks:1.3.0
|    |    \--- com.parse.bolts:bolts-tasks:1.3.0
|    +--- com.android.support:multidex:1.0.1
|    +--- com.parse.bolts:bolts-tasks:1.3.0
|    +--- com.android.support:support-v4:(23,24] -> 23.1.1
|    \--- com.android.support:cardview-v7:(23,24] -> 23.1.1
[…]
```
I don't need the transitive dependency `com.android.support:multidex:1.0.1`. By removing the `multiDexEnabled true` flag from the transitive dependency is removed as well.

Remove multiDexEnabled flag

---

facebook/src/main/java/com/facebook/internal/NativeProtocol.java

Noticed you had this vulnerability. https://www.blackhat.com/docs/us-14/materials/us-14-Forristal-Android-FakeID-Vulnerability-Walkthrough.pdf
For further reference, see the Uber SDK implementation and associated tests
(Putting on Dev instead Master.)

Fix Fake ID exploit

---

facebook/src/main/java/com/facebook/GraphRequest.java

On iOS, this works:
GraphRequest("/me?fields=id")
On Android, it does not, and the resulting URL looks like:
"/me?fields=id?access_token=X&other=params&included=here" (notice the two "?" chars)
This causes a very strange problem when react-native-fbsdk assumes they perform identically, as seen here:
facebook/react-native-fbsdk#105
This should fix the issue and bring feature parity between iOS and Android.

Fix request parsing to handle any passed-in request parameters

---

facebook/src/main/java/com/facebook/internal/NativeProtocol.java

Hello,
We're having several crashes from DeadObjectExceptions while accessing the ContentProvider. This code should prevent it to crash the entire app, following the same politic than in line 892.
The stacktrace of the crash is:
> java.lang.RuntimeException: Package manager has died
at android.app.ApplicationPackageManager.resolveContentProviderAsUser(ApplicationPackageManager.java:721)
at android.app.ApplicationPackageManager.resolveContentProvider(ApplicationPackageManager.java:712)
at com.facebook.internal.NativeProtocol.fetchAllAvailableProtocolVersionsForAppInfo(SourceFile:786)
at com.facebook.internal.NativeProtocol.access$000(SourceFile:49)
at com.facebook.internal.NativeProtocol$NativeAppInfo.fetchAvailableVersions(SourceFile:281)
at …

Prevent the app from crash if a DeadObjectException happens in the ContentProvider

---

facebook/build.gradle

We use latest versions of dependencies on moment of release and when we include facebook-sdk it forces us to use old version of com.android.support. I believe that's common pattern to work with dependencies. Especially when it's provided by Google.

Updated com.android.support to the latest version

---

facebook/src/main/java/com/facebook/internal/Validate.java

The previous check `activityInfo.name.equals(CustomTabActivity.class.getName()` was just verifying that the advertising app has a CustomTabActivity, not that _this_ app has a CustomTabActivity.  This means a malicious app could advertise their own CustomTabActivity and collect facebook credentials for their own uses.

Security issue: actually validate that the package name matches the current app

---

README.mdown

The following error occurred when I tried to install Facebook SDK 4.27.0 in my app.
```
Error:(237, 13) Failed to resolve: com.facebook.android:facebook-core:4.27
```
The cause of this error is mistaken version number in README. So I fixed this from `4.27` to `4.27.0`.

Fixed version number in README (4.27 -> 4.27.0)

---

samples/Scrumptious/src/com/example/scrumptious/SelectionFragment.java

`R.string.multiple_users_selected` is expecting both arguments to be a string so fix the warning by converting int to string in the Scrumptious example.

Convert int to string to remove wrong argument warning

---

README.mdown

After the Gradle 3.0, compile is now deprecated and no longer used.
It should be replaced with implementation 
cf: https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_separation
Thanks for proposing a pull request.
To help us review the request, please complete the following:

replace compile with implementation

---

facebook-core/src/main/java/com/facebook/AccessTokenManager.java

check argument token expiration.
I think it's better to checking argument token before set.
It will be resolve some token expired situation maybe.
I updated similar logic on iOS repository.
Thanks for proposing a pull request.
To help us review the request, please complete the following:

setCurrentAccessToken changed.
